# Importing Libraries

In [32]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Getting the Data

In [33]:
from sklearn.datasets import load_breast_cancer # built-in dataset

In [34]:
cancer = load_breast_cancer()

In [35]:
cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [36]:
print(cancer['DESCR'])

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

# Setting Up DataFrame

In [37]:
df_feat = pd.DataFrame(cancer['data'], columns=cancer['feature_names'])

In [38]:
df_feat.head(3)

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38           122.8     1001.0          0.11840   
1        20.57         17.77           132.9     1326.0          0.08474   
2        19.69         21.25           130.0     1203.0          0.10960   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33            184.6   
1                 0.05667  ...         24.99          23.41            158.8   
2                 0.05999  ...         23.57          25.53            152.5   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  

[3 rows x 30 columns]

In [39]:
df_feat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 30 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [40]:
cancer['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [41]:
cancer['target_names']

array(['malignant', 'benign'], dtype='<U9')

# Train Test Split

In [42]:
from sklearn.model_selection import train_test_split

In [44]:
X = df_feat
y = cancer['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=10)

In [45]:
X_train

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
431        12.40         17.68           81.47      467.8          0.10540   
389        19.55         23.21          128.90     1174.0          0.10100   
309        13.05         13.84           82.71      530.6          0.08352   
111        12.63         20.76           82.15      480.4          0.09933   
35         16.74         21.59          110.10      869.5          0.09610   
..           ...           ...             ...        ...              ...   
369        22.01         21.90          147.20     1482.0          0.10630   
320        10.25         16.18           66.52      324.2          0.10610   
527        12.34         12.27           78.94      468.5          0.09003   
125        13.85         17.21           88.44      588.7          0.08785   
265        20.73         31.12          135.70     1419.0          0.09469   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
431           0.13160        0.077410             0.027990         0.1811   
389           0.13180        0.185600             0.102100         0.1989   
309           0.03735        0.004559             0.008829         0.1453   
111           0.12090        0.106500             0.060210         0.1735   
35            0.13360        0.134800             0.060180         0.1896   
..                ...             ...                  ...            ...   
369           0.19540        0.244800             0.150100         0.1824   
320           0.11110        0.067260             0.039650         0.1743   
527           0.06307        0.029580             0.026470         0.1689   
125           0.06136        0.014200             0.011410         0.1614   
265           0.11430        0.136700             0.086460         0.1769   

     mean fractal dimension  ...  worst radius  worst texture  \
431                 0.07102  ...         12.88          22.91   
389                 0.05884  ...         20.82          30.44   
309                 0.05518  ...         14.73          17.40   
111                 0.07070  ...         13.33          25.47   
35                  0.05656  ...         20.01          29.02   
..                      ...  ...           ...            ...   
369                 0.06140  ...         27.66          25.80   
320                 0.07279  ...         11.28          20.61   
527                 0.05808  ...         13.61          19.27   
125                 0.05890  ...         15.49          23.58   
265                 0.05674  ...         32.49          47.16   

     worst perimeter  worst area  worst smoothness  worst compactness  \
431            89.61       515.8            0.1450            0.26290   
389           142.00      1313.0            0.1251            0.24140   
309            93.96       672.4            0.1016            0.05847   
111            89.00       527.4            0.1287            0.22500   
35            133.50      1229.0            0.1563            0.38350   
..               ...         ...               ...                ...   
369           195.00      2227.0            0.1294            0.38850   
320            71.53       390.4            0.1402            0.23600   
527            87.22       564.9            0.1292            0.20740   
125           100.30       725.9            0.1157            0.13500   
265           214.00      3432.0            0.1401            0.26440   

     worst concavity  worst concave points  worst symmetry  \
431          0.24030               0.07370          0.2556   
389          0.38290               0.18250          0.2576   
309          0.01824               0.03532          0.2107   
111          0.22160               0.11050          0.2226   
35           0.54090               0.18130          0.4863   
..               ...                   ...             ...   
369          0.47560               0.24320         

In [46]:
y_train

array([1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,

In [47]:
X_test

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
172       15.460         11.89          102.50      736.9          0.12570   
553        9.333         21.94           59.01      264.0          0.09240   
374       13.690         16.07           87.84      579.1          0.08302   
370       16.350         23.29          109.00      840.4          0.09742   
419       11.160         21.41           70.95      380.3          0.10180   
..           ...           ...             ...        ...              ...   
108       22.270         19.67          152.80     1509.0          0.13260   
458       13.000         25.13           82.61      520.2          0.08369   
173       11.080         14.71           70.21      372.7          0.10060   
240       13.640         15.60           87.38      575.3          0.09423   
436       12.870         19.54           82.67      509.2          0.09136   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
172           0.15550        0.203200              0.10970         0.1966   
553           0.05605        0.039960              0.01282         0.1692   
374           0.06374        0.025560              0.02031         0.1872   
370           0.14970        0.181100              0.08773         0.2175   
419           0.05978        0.008955              0.01076         0.1615   
..                ...             ...                  ...            ...   
108           0.27680        0.426400              0.18230         0.2556   
458           0.05073        0.012060              0.01762         0.1667   
173           0.05743        0.023630              0.02583         0.1566   
240           0.06630        0.047050              0.03731         0.1717   
436           0.07883        0.017970              0.02090         0.1861   

     mean fractal dimension  ...  worst radius  worst texture  \
172                 0.07069  ...        18.790          17.04   
553                 0.06576  ...         9.845          25.05   
374                 0.05669  ...        14.840          20.21   
370                 0.06218  ...        19.380          31.03   
419                 0.06144  ...        12.360          28.92   
..                      ...  ...           ...            ...   
108                 0.07039  ...        28.400          28.01   
458                 0.05449  ...        14.340          31.88   
173                 0.06669  ...        11.350          16.82   
240                 0.05660  ...        14.850          19.05   
436                 0.06347  ...        14.450          24.38   

     worst perimeter  worst area  worst smoothness  worst compactness  \
172           125.00      1102.0            0.1531            0.35830   
553            62.86       295.8            0.1103            0.08298   
374            99.16       670.6            0.1105            0.20960   
370           129.30      1165.0            0.1415            0.46650   
419            79.26       458.0            0.1282            0.11080   
..               ...         ...               ...                ...   
108           206.80      2360.0            0.1701            0.69970   
458            91.06       628.5            0.1218            0.10930   
173            72.01       396.5            0.1216            0.08240   
240            94.11       683.4            0.1278            0.12910   
436            95.14       626.9            0.1214            0.16520   

     worst concavity  worst concave points  worst symmetry  \
172          0.58300               0.18270          0.3216   
553          0.07993               0.02564          0.2435   
374          0.13460               0.06987          0.3323   
370          0.70870               0.22480          0.4824   
419          0.03582               0.04306          0.2976   
..               ...                   ...             ...   
108          0.96080               0.29100         

In [48]:
y_test

array([0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1])

# Training the Support Vector Classifier

In [49]:
from sklearn.svm import SVC

In [50]:
model = SVC()

In [51]:
model.fit(X_train, y_train)

SVC()

# Predictions and Evaluations

In [52]:
predictions = model.predict(X_test)

In [53]:
from sklearn.metrics import classification_report, confusion_matrix

In [54]:
print(confusion_matrix(y_test, predictions))
print('\n')
print(classification_report(y_test, predictions))

[[ 51   8]
 [  3 109]]


              precision    recall  f1-score   support

           0       0.94      0.86      0.90        59
           1       0.93      0.97      0.95       112

    accuracy                           0.94       171
   macro avg       0.94      0.92      0.93       171
weighted avg       0.94      0.94      0.93       171



# Gridsearch

A grid search will exhaustively test all possible combinations of these hyperparameters, training an SVM for each set. The grid search will then report the best hyperparameters (i.e., the ones that maximized accuracy).

In [55]:
from sklearn.model_selection import GridSearchCV

In [56]:
param_grid = {'C':[0.1,1,10,100,1000], 'gamma':[1,0.1,0.01,0.001,0.0001]}

In [57]:
grid = GridSearchCV(SVC(), param_grid, verbose = 3)

In [58]:
grid.fit(X_train,y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ....................C=0.1, gamma=1;, score=0.613 total time=   0.0s
[CV 2/5] END ....................C=0.1, gamma=1;, score=0.613 total time=   0.0s
[CV 3/5] END ....................C=0.1, gamma=1;, score=0.613 total time=   0.0s
[CV 4/5] END ....................C=0.1, gamma=1;, score=0.620 total time=   0.0s
[CV 5/5] END ....................C=0.1, gamma=1;, score=0.620 total time=   0.0s
[CV 1/5] END ..................C=0.1, gamma=0.1;, score=0.613 total time=   0.0s
[CV 2/5] END ..................C=0.1, gamma=0.1;, score=0.613 total time=   0.0s
[CV 3/5] END ..................C=0.1, gamma=0.1;, score=0.613 total time=   0.0s
[CV 4/5] END ..................C=0.1, gamma=0.1;, score=0.620 total time=   0.0s
[CV 5/5] END ..................C=0.1, gamma=0.1;, score=0.620 total time=   0.0s
[CV 1/5] END .................C=0.1, gamma=0.01;, score=0.613 total time=   0.0s
[CV 2/5] END .................C=0.1, gamma=0.01

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001]},
             verbose=3)

In [59]:
grid.best_params_

{'C': 10, 'gamma': 0.0001}

In [60]:
grid.best_estimator_

SVC(C=10, gamma=0.0001)

In [61]:
grid_predictions = grid.predict(X_test)

In [62]:
print(confusion_matrix(y_test,grid_predictions))
print('\n')
print(classification_report(y_test,grid_predictions))

[[ 55   4]
 [  6 106]]


              precision    recall  f1-score   support

           0       0.90      0.93      0.92        59
           1       0.96      0.95      0.95       112

    accuracy                           0.94       171
   macro avg       0.93      0.94      0.94       171
weighted avg       0.94      0.94      0.94       171

